### ISSUE TITLE
Quarkus startup error logs seem to disapperar

### ISSUE THREAD

**Issue by heineson** [quarkiverse/quarkus-logging-logback#135]
Hello!

Really appreciating this plugin, makes migrating to Quarkus a lot easier for us in regards to log setup. I just noticed one thing however, which I can't see that it is my own fault. When enabling this plugin Quarkus startup errors seem to disapperar. Before adding the extension to our pom.xml, everything from Quarkus is logged as expected but after I just see nothing in the logs. Any idea what might be wrong? 

Extension used:

```
    <dependency>
      <groupId>io.quarkiverse.logging.logback</groupId>
      <artifactId>quarkus-logging-logback</artifactId>
      <version>1.1.0</version>
    </dependency>
```
    
Expected error in log:

`2023-06-26 11:06:16,080 ERROR io.quarkus.runtime.Application  - Failed to start application (with profile [dev]): ...`

**Comment by Angel0926** [comment]
this problem was still when the version was updated to  <dependency>
      <groupId>io.quarkiverse.logging.logback</groupId>
      <artifactId>quarkus-logging-logback</artifactId>
      <version>1.0.0</version>
    </dependency>

**Comment by GinaGeorgescul** [comment]
Hello! Wondering if there is any fix planned for this issue?

**Comment by Angel0926** [comment]
I fixed that with upgrading dependency slf4j.jboss.logmanager from 1.x.x version to <slf4j.jboss.logmanager>2.0.1.Final</slf4j.jboss.logmanager>.

org.jboss.slf4j
slf4j-jboss-logmanager
${slf4j.jboss.logmanager} 



but in my question Maybe this update was previously passed automatically? they answer

" If you are still using Quarkus 2.x, you should keep Quarkus Logging Logback 0.x.

If you upgrade to Quarkus 3.x, then upgrade it to 1.0.0 and things will work out of the box."

**Comment by gsmet** [comment]
Isn't `slf4j-jboss-logmanager` in our BOM? I'm surprised you have to manage the version yourself?

**Comment by GinaGeorgescul** [comment]
It is, and for me overriding it with a different version did not fix the issue. 
Hibernate startup validation failure is still not logged. 

The extension used is: `<dependency>
      <groupId>io.quarkiverse.logging.logback</groupId>
      <artifactId>quarkus-logging-logback</artifactId>
      <version>0.13.0</version>
    </dependency>`  I tried overriding the 1.2.0.Final slf4j-jboss-logmanager with 2.0.1.Final

**Comment by Angel0926** [comment]
@gsmet I didn't understand your question, I just used this dependency and it worked and below I just quoted your answer to my question

**Comment by gsmet** [comment]
I don't think I will have the cycles to look into this anytime soon so I would recommend you all have a look with a debugger and try to understand what's going on.
Might not be easy though, I have no idea.
